CLASSIFICATION_PROMPT = """
You are a school threat assessment AI. Analyze the following tip transcript and extract structured information.

Transcript:
{transcript}

Return a JSON object with exactly these fields:
{{
  "threat_level": <integer 1-5, where 5 is most severe>,
  "threat_type": <one of: weapon, bullying, drugs, threat, self_harm, vandalism, harassment, other>,
  "school_name": <extracted school name or null>,
  "location_detail": <any specific location mentioned or null>,
  "timeline": <immediate/today/this_week/unknown>,
  "named_subject": <full name of the specific person being threatened or of concern (e.g. "Max Higgins") or null>,
  "subject_description": <physical/contextual description of person of concern or null>,
  "key_facts": [<list of 3-5 bullet point facts>],
  "recommended_action": <one of: immediate_911, notify_principal, monitor, document>,
  "confidence": <float 0.0-1.0>,
  "summary": <2-3 sentence plain English summary for the threat brief>,
  "caller_emotion": <one of: calm, anxious, panicked, distressed, detached>,
  "caller_tone": <one of: urgent, casual, matter_of_fact, emotional, guarded>,
  "credibility_signals": [<list of 1-3 specific details that increase or decrease credibility>],
  "escalation_risk": <one of: stable, escalating, imminent>
}}

Return only the JSON object. No commentary.
"""

FOLLOWUP_QUESTIONS_PROMPT = """
You are a calm, professional school safety intake agent on a phone call.
The caller has just said: "{initial_statement}"

Generate 3 short follow-up questions to gather critical details.
Focus on: specific location, timeline (is this happening now?), description of the person involved.
Keep questions under 15 words each. Return as a JSON array of strings.
"""

EMAIL_BRIEF_PROMPT = """
Write a formal threat assessment brief email for a district safety officer.

Tip data:
{tip_data}

Format:
- Subject line first (prefix with SUBJECT:)
- Then the email body
- Professional, factual tone
- Include: threat level, school, key facts, recommended action, timestamp
- No speculation beyond the facts
- End with: "This report was generated by Threat Vector. A copy has been logged to the Aegis safety dashboard."
"""
